import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { LIMITS } from "../src/contracts/limits";

const dest = resolve(__dirname, "../../frontend/src/generated/api.ts");

const contents = `/* Generated by backend/scripts/export-contracts.ts — do not edit by hand */

export const LIMITS = ${JSON.stringify(LIMITS, null, 2)} as const;

export type Role = "user" | "assistant" | "system" | "tool";
export type MessageStatus = "success" | "failed" | "cancelled";
export type RunStatus =
  | "queued"
  | "thinking"
  | "working"
  | "waiting"
  | "stopping"
  | "complete"
  | "failed"
  | "cancelled";

export type ContentBlock =
  | { type: "text"; text: string }
  | { type: "thinking"; text: string; durationMs?: number }
  | { type: "tool_use"; invocationId: string; toolName: string; input: unknown }
  | {
      type: "tool_result";
      invocationId: string;
      toolName: string;
      output: unknown;
      status: MessageStatus;
    }
  | { type: "reasoning"; text: string }
  | { type: "citations"; items: { url?: string; title?: string; text?: string }[] }
  | {
      type: "usage";
      modelRouted: string | null;
      promptTokens: number;
      completionTokens: number;
      applicationCredits: number;
    };

export type ErrorEnvelope = {
  error: string;
  message: string;
  code: string;
  traceId: string;
};

export type Chat = {
  id: string;
  title: string;
  favorited: boolean;
  pinned: boolean;
  activeRunId: string | null;
  createdAt: string;
  updatedAt: string;
};

export type ChatListResponse = {
  items: Chat[];
  nextCursor: string | null;
};

export type Message = {
  id: string;
  chatId: string;
  runId: string | null;
  role: Role;
  status: MessageStatus;
  blocks: ContentBlock[];
  createdAt: string;
};

export type MessageListResponse = {
  items: Message[];
  nextCursor: string | null;
};

export type SendTurnRequest = {
  text: string;
  model?: "openrouter/free";
  clientIdempotencyKey: string;
  attachmentIds?: string[];
  planMode?: boolean;
};

export type WaitpointKind = "options" | "plan" | "credit" | "media";
export type WaitpointStatus = "open" | "approved" | "rejected" | "expired";

export type Waitpoint = {
  id: string;
  token: string;
  runId: string;
  kind: WaitpointKind;
  payload: {
    title: string;
    summary: string;
    estimateCredits?: number;
    toolName?: string;
    mediaUrls?: string[];
    choices?: { id: string; label: string }[];
    selectedChoiceId?: string;
  };
  status: WaitpointStatus;
  resumeKey: string;
  expiresAt: string;
  createdAt: string;
};

export type GeneratedAsset = {
  id: string;
  kind: "image" | "video" | "audio";
  url: string;
  durableUrl: string | null;
  mimeType: string | null;
  createdAt: string;
};

export type SendTurnResponse = {
  chatId: string;
  messageId: string;
  runId: string;
  realtime: {
    transport: "poll" | "trigger" | "sse";
    pollUrl: string;
    eventsUrl?: string;
  };
};

export type Attachment = {
  id: string;
  mimeType: string;
  originalName: string;
  resultUrl: string | null;
  durableUrl: string | null;
  sortOrder: number;
};

export type RunResponse = {
  id: string;
  chatId: string;
  status: RunStatus;
  modelRequested: string;
  modelRouted: string | null;
  userMessageId: string;
  assistantMessageId: string | null;
  errorCode: string | null;
  errorSafeMessage: string | null;
  assistant: Message | null;
  waitpoint: Waitpoint | null;
  generatedAssets: GeneratedAsset[];
  createdAt: string;
};

export type CreditsResponse = {
  balance: number;
};
`;

mkdirSync(dirname(dest), { recursive: true });
writeFileSync(dest, contents);
console.log("Wrote " + dest);
